### ISSUE TITLE
synchronize:(SyncMode)syncMode complete:(CompleteBlock)complete

### ISSUE THREAD

**Issue by zhoupIT** [Seanwong933/TO-DO#3]
这个里面的operation不需要不放到queue里面么

**Comment by siegrainwong** [comment]
你问地有点绕，能不能更具体的描述一下。
外面的队列是我加的同步锁，里面的operation是并行的异步队列。

**Comment by zhoupIT** [comment]
不太明白,为啥用NSBlockOperation呢,我看你也用了gcd

**Comment by siegrainwong** [comment]
一开始其实也用的GCD，后来发现GCD不能取消，就换成了NSOperationQueue，主要是需求原因。
