### ISSUE TITLE
运行你的项目 说图片找不到，也不知道哪个图片找不到

### ISSUE THREAD

**Issue by wo364379560** [Seanwong933/TO-DO#6]
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/CCDE0DD8-FBE1-428D-A1D9-337DC3CC0AA4/TO-DO.app/TO-DO
  Reason: image not found
Message from debugger: Terminated due to signal 6

**Comment by wo364379560** [comment]
试了 多次也不行

**Comment by siegrainwong** [comment]
https://stackoverflow.com/questions/20340763/xcode-5-0-2-dyld-library-not-loaded-rpath-xctest-framework-versions-a-xctest
https://blog.csdn.net/gaomingyangc/article/details/55657054

不好意思，手上没有mac，帮你google了一下，那个image并不是图片的意思，是镜像的意思。
